# Generated by Django 3.1.2 on 2020-10-03 22:54

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('motto', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('points', models.IntegerField(default=0)),
                ('education', models.ManyToManyField(blank=True, related_name='students', to='spaceAgeContact.School')),
                ('followers', models.ManyToManyField(blank=True, related_name='follower', to='spaceAgeContact.User')),
                ('following', models.ManyToManyField(blank=True, related_name='followings', to='spaceAgeContact.User')),
                ('work', models.ManyToManyField(blank=True, related_name='workers', to='spaceAgeContact.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('members', models.ManyToManyField(to='spaceAgeContact.User')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('total_space_dust', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('num_correct_answers', models.IntegerField()),
                ('players', models.ManyToManyField(related_name='player', to='spaceAgeContact.User')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceAgeContact.gametopic')),
            ],
        ),
    ]
