# Generated by Django 3.1.2 on 2020-10-03 17:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('motto', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('points', models.IntegerField()),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceAgeContact.school')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceAgeContact.job')),
            ],
        ),
    ]
