# Generated by Django 3.1.2 on 2020-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceAgeContact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='non', max_length=100),
            preserve_default=False,
        ),
    ]
