# Generated by Django 3.1.2 on 2020-10-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceAgeContact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(to='spaceAgeContact.School'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='work',
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.ManyToManyField(to='spaceAgeContact.Job'),
        ),
    ]
