# Generated by Django 3.1.2 on 2020-10-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceAgeContact', '0002_auto_20201003_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('members', models.ManyToManyField(to='spaceAgeContact.User')),
            ],
        ),
    ]
