# Generated by Django 3.1.2 on 2020-10-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceAgeContact', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('total_space_dust', models.IntegerField()),
                ('duration', models.FloatField()),
                ('num_correct_answers', models.IntegerField()),
                ('players', models.ManyToManyField(to='spaceAgeContact.User')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceAgeContact.gametopic')),
            ],
        ),
    ]
