# Generated by Django 3.1.2 on 2020-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceAgeContact', '0004_game_gametopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
