# Generated by Django 3.1.2 on 2020-10-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceAgeContact', '0005_auto_20201003_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_followers_+', to='spaceAgeContact.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_following_+', to='spaceAgeContact.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='spaceAgeContact.School'),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='work',
            field=models.ManyToManyField(blank=True, null=True, to='spaceAgeContact.Job'),
        ),
    ]
